# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-13 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiantai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格'),
        ),
    ]
