# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qiantai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='订单时间')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单总额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiantai.UserInfo')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单详细信息')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiantai.Goods')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
    ]
